### ISSUE TITLE
is this trying to grab my ip

### ISSUE THREAD

**Issue by FireKoopaX** [hanaui-git/ZeroDiscord#14]
Ok so when i look at the code for the tokenstealer it shows that i need something called public-ip to get it to work
i'm pretty new to this stuff, so i'm not too sure what it's trying to do when i run it and theres some ip stuff in there

**Comment by I2rys** [comment]
Hello @FireKoopaX,
The reason It has a library for grabbing an IP is when someone open the compiled version It will also send that someone's IP address, computer host name, username & etc in the Discord webhook that is set. Also I'm not sure If It will still work because Discord added some extra protection.

![image](https://user-images.githubusercontent.com/87125939/201608945-ae61dea8-c8b2-4280-b71c-bda6128ea354.png)

**Comment by FireKoopaX** [comment]
oh alright, thanks for clearing that up
